before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - node_modules/.bin/buster-server &
  - sleep 5
  - firefox http://localhost:1111/capture &
  - sleep 5
  - npm install -g bower
  - bower install --production
  - bower install jquery#$JQUERY_VERSION

script:
  - "node_modules/.bin/buster test -r specification"

language: node_js

node_js:
  - 0.8

env:
  - JQUERY_VERSION=1.4
  - JQUERY_VERSION=1.8
  - JQUERY_VERSION=*
